version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: windjammers_tournaments_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - windjammers-tournaments-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: windjammers_tournaments_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - windjammers-tournaments-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: windjammers_tournaments_db
    restart: unless-stopped
    tty: true
    ports:
      - "3311:3311"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: mysql_root_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      MYSQL_TCP_PORT: 3311
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - windjammers-tournaments-network

#Docker Networks
networks:
  windjammers-tournaments-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
